<?php
require "../config.php";
require "../common.php";

// Create indexes on specific attributes (e.g., driverName)
try {
    $connection = new PDO($dsn, $username, $password, $options);
    $connection->setAttribute(PDO::ATTR_ERRMODE, PDO::ERRMODE_EXCEPTION);


} catch (PDOException $error) {
    echo $indexSql . "<br>" . $error->getMessage();
}

$userOption = "";

try {
    $connection = new PDO($dsn, $username, $password, $options);
    $connection->setAttribute(PDO::ATTR_ERRMODE, PDO::ERRMODE_EXCEPTION);


    $sql = "SELECT * FROM users";
    $result = $connection->query($sql);

    if ($result->rowCount() > 0) {
        foreach ($result as $row) {
            $user_id = $row["user_id"];
            $name = $row["name"];
            $useroption .= "<option value='$user_id'>$name</option>";
        }
    } else {
        $useroption = "<option value='0'>No users available</option>";
    }
} catch (PDOException $error) {
    echo $sql . "<br>" . $error->getMessage();
}

if (isset($_POST['submit'])) {
    if (!hash_equals($_SESSION['csrf'], $_POST['csrf'])) {
        die("CSRF token mismatch");
    }

    try {
        $connection->beginTransaction();

        $new_trip = [
            "trip_id" => $_POST['trip_id'],
            "startlocation" => $_POST['startlocation'],
            "endlocation" => $_POST['endlocation'],
            "tripdays" => $_POST['tripdays'],
            "vehicletype" => $_POST['vehicletype'],
            "Date" => $_POST['Date'],
        ];

        $sql = sprintf(
            "INSERT INTO %s (%s) VALUES (%s)",
            "trips",
            implode(", ", array_keys($new_trip)),
            ":" . implode(", :", array_keys($new_trip))
        );

        $statement = $connection->prepare($sql);
        $statement->execute($new_trip);

        // The tripNo is automatically generated by the database

        if (!empty($_POST["users"])) {
            $tripNo = $connection->lastInsertId(); // Get the auto-generated tripNo
            foreach ($_POST["users"] as $user_id) {
                $sql = "INSERT INTO users (trip_id, user_id) VALUES (:trip_id, :user_id)";
                $stmt = $connection->prepare($sql);
                $stmt->execute([':trip_id' => $trip_id, ':user_id' => $user_id]);
            }
        }

        $connection->commit(); // Commit the transaction
        echo "Trip successfully added.";
    } catch (PDOException $error) {
        $connection->rollBack(); // Roll back the transaction if an error occurred
        echo "Error: " . $error->getMessage();
    }
}
?>

<?php require "templates/header.php"; ?>

<?php if (isset($_POST['submit'])) : ?>
    <blockquote>Trip successfully added.</blockquote>
<?php endif; ?>

<h2>Add a Trip</h2>

<form method="post">
    <input name="csrf" type="hidden" value="<?php echo escape($_SESSION['csrf']); ?>">
    <label for="trip_id">Trip ID</label>
    <input type="text" name="trip_id" id="trip_id">
    <label for="user_id">User ID Number</label>
    <input type="text" name="user_id" id="user_id">
    <label for="startlocation">Start Location</label>
    <input type="text" name="startlocation" id="startlocation">
    <label for="endlocation">End Location</label>
    <input type="text" name="endlocation" id="endlocation">
    <label for="tripdays">How many days you want vehicle</label>
    <input type="text" name="tripdays" id="tripdays">
    <label for="vehicletype">Vehicle Type</label>
    <input type="text" name="vehicletype" id="vehicletype">
    <label for="Date">Date</label>
    <input type="Date" name="Date" id="Date">

    <label for="users">Enter user ID</label>
    <select multiple name="users[]" id="users">
        <?php echo $useroption; ?>
    </select>
    <input type="submit" name="submit" value="Submit">
</form>

<a href="createuser.php"><strong>Users</strong></a><br>
<a href="index.php"><strong>Back to Trip Home</strong></a><br>
<a href="home.php"><strong>Back to Home</strong></a>

<?php require "templates/footer.php"; ?>
